package it.eudata.fastweb.retrieveAccountIndicators.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2019-03-19T17:41:23.688+01:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://it.fastweb.esb.org/RetrieveAccountIndicators", name = "RetrieveAccountIndicatorsPortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface RetrieveAccountIndicatorsPortType {

    @WebMethod(operationName = "RetrieveAccountIndicators", action = "RetrieveAccountIndicators")
    @WebResult(name = "RetrieveAccountIndicatorsResponse", targetNamespace = "http://it.fastweb.esb.org/RetrieveAccountIndicators", partName = "RetrieveAccountIndicatorsResponse")
    public RetrieveAccountIndicatorsResponseType retrieveAccountIndicators(
        @WebParam(partName = "RetrieveAccountIndicatorsRequest", name = "RetrieveAccountIndicatorsRequest", targetNamespace = "http://it.fastweb.esb.org/RetrieveAccountIndicators")
        RetrieveAccountIndicatorsRequestType retrieveAccountIndicatorsRequest
    );
}
