
package it.eudata.fastweb.retrieveAccountIndicators.soap;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2019-03-19T17:41:23.623+01:00
 * Generated source version: 3.1.5
 * 
 */
public final class RetrieveAccountIndicatorsPortType_RetrieveAccountIndicatorsPort_Client {

    private static final QName SERVICE_NAME = new QName("http://it.fastweb.esb.org/RetrieveAccountIndicators", "RetrieveAccountIndicatorsService");

    private RetrieveAccountIndicatorsPortType_RetrieveAccountIndicatorsPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = RetrieveAccountIndicatorsService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RetrieveAccountIndicatorsService ss = new RetrieveAccountIndicatorsService(wsdlURL, SERVICE_NAME);
        RetrieveAccountIndicatorsPortType port = ss.getRetrieveAccountIndicatorsPort();  
        
        {
        System.out.println("Invoking retrieveAccountIndicators...");
        it.eudata.fastweb.retrieveAccountIndicators.soap.RetrieveAccountIndicatorsRequestType _retrieveAccountIndicators_retrieveAccountIndicatorsRequest = null;
        it.eudata.fastweb.retrieveAccountIndicators.soap.RetrieveAccountIndicatorsResponseType _retrieveAccountIndicators__return = port.retrieveAccountIndicators(_retrieveAccountIndicators_retrieveAccountIndicatorsRequest);
        System.out.println("retrieveAccountIndicators.result=" + _retrieveAccountIndicators__return);


        }

        System.exit(0);
    }

}
